@VatCalculatorAPI_HostAddress = http://localhost:5221

POST {{VatCalculatorAPI_HostAddress}}/api/vatcalculator/calculate
Content-Type: application/json

{
  "netAmount": "100",
  "vatRate": "20"
}

###
